apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: nexaflow
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: nexaflow-api:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "-m", "production.kafka.consumer"]
          envFrom:
            - secretRef:
                name: nexaflow-secrets
            - configMapRef:
                name: nexaflow-config
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
